config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'faq', to: 'pages#faq'
  # resources :articles, only: %i[show index new create edit update destroy]
  resources :articles
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: %i[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  before_save do
    self.email = email.downcase
    self.username = username.downcase
  end
  validates :username,
            presence: true,
            length: {
              minimum: 3,
              maximum: 50
            },
            uniqueness: {
              case_sensitive: false
            }
  validates :email,
            presence: true,
            length: {
              maximum: 105
            },
            uniqueness: {
              case_sensitive: false
            },
            format: {
              with: VALID_EMAIL
            }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user,
                :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    # find_article
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit
    # find_article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'article was successfully created'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    # find_article
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article #{params[:id]} was successfully destroyed"
    redirect_to articles_path
  end


  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or destroy your own article'
      redirect_to @article
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: %i[index show]

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(categories_params)
      flash[:notice] = 'That category was updated'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  private

  def categories_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about; end

  def faq; end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    user = User.find_by(email: email)
    if user && user.authenticate(password)
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong, we can\'t find your account!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out successfully'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 1)
  end

  def new
    @user = User.new
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'You have successfully edit your account data'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Successfully signed in'
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'That bullshit account and all it\'s fucking associated articles was destroyed :|'
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or destroy your own account'
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 800 })
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.username)
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |msg| %>
    <%= msg %><br/>
  <% end %>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.collection_select(
          :category_ids,
          Category.all,
          :id,
          :name,
          { prompt: 'Make your selection from the list below (can be empty)' },
          {
            multiple: true,
            class: 'custom-select rounded'
          }
        ) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_table.html.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>id</th>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
    <th>Categories</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 0 %>
  <% @articles.each do |article| %>
    <tr>
      <td><%= index += 1 %></td>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.user.username if article.user %></td> <!-- if is temp -->
      <td>
        <% if article.categories.any? %>
            <%= render article.categories %>
        <% else %>
          No categories specified!
        <% end %>
      </td>
      <td>
        <%= link_to "Visit",
                    article_path(article),
                    class: 'btn btn-primary' %>
        <% if logged_in? && (article.user.id === current_user.id || current_user.admin?) %>
          <%= link_to "Destroy",
                      article_path(article),
                      method: :delete,
                      data: {
                        confirm: "Are you really ok with destroying \"#{article.title}\""
                      },
                      class: 'btn btn-danger' %>
          <%= link_to "Edit",
                      edit_article_path(article),
                      class: 'btn btn-warning' %>
        <% end %>
      </td>
    </tr>
  <% end %>


  </tbody>
</table>

app/views/articles/edit.html.erb
<h1>Edit new article</h1>

<%= render 'form' %>

<p>
You can also <%= link_to "get outta here", articles_path  %>
</p>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<%= render 'table' %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

<a class='btn btn-success' href='/articles/new'>Create new Article</a>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render 'form' %>

<p>
You can also <%= link_to "get outta here", articles_path  %>
</p>

app/views/articles/show.html.erb
<h1>Review Article</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<p>
  By
  <%= link_to @article.user.username, @article.user %>
</p>

<% if @article.categories.any? %>
<p>
  Categories:
  <%= render @article.categories %>
</p>
<% end %>


<p>
  You can
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to "Edit this Article", edit_article_path(@article), class: 'btn btn-warning' %>
    or
    <%= link_to "Remove it", article_path(@article),
                method: :delete,
                data: { confirm: "Are you really ok with destroying \"#{@article.title}\"" },
                class: 'btn btn-danger'
    %>
    or
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</p>

app/views/categories/_category.html.erb
<span>
  <%=
    link_to "##{category.name.downcase.gsub(' ', '_')}",
            category_path(category),
            class: 'badge badge-pill badge-secondary'
  %>
</span>

app/views/categories/_form.html.erb
<% if @category.errors.any?  %>
  repair following errors:
  <% @category.errors.full_messages.each do |msg| %>
    <p class='for_test'><%= msg %></p><br/>
  <% end %>
<% end %>


<%= form_with(model: @category, local: true) do |f| %>
  <p>
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/_table.html.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>id</th>
    <th>Name</th>
    <th>Articles</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 0 %>
  <% @categories.each do |category| %>
    <tr>
      <td><%= index += 1 %></td>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td><%= pluralize(category.articles.count, 'article') %></td>
      <td>
        <%= link_to "Visit",
                    category_path(category),
                    class: 'btn btn-primary' %>
        <% if logged_in? &&  current_user.admin? %>
          <%= link_to "Destroy",
                      category_path(category),
                      method: :delete,
                      data: {
                        confirm: "Are you really ok with destroying \"#{category.name}\""
                      },
                      class: 'btn btn-danger' %>
          <%= link_to "Edit",
                      edit_category_path(category),
                      class: 'btn btn-warning' %>
        <% end %>
      </td>
    </tr>
  <% end %>


  </tbody>
</table>

app/views/categories/edit.html.erb
<h1>Edit new category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Articles listing page</h1>

<%= render 'table' %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
  <%= will_paginate @categories, :container => false %>
</div>

<a class='btn btn-success' href='/categories/new'>Create new Category</a>

app/views/categories/new.html.erb
<h1>Create new category</h1>

<%= render 'form' %>

<p>
  You can also <%= link_to "get outta here", articles_path  %>
</p>

app/views/categories/show.html.erb
Category: <%= @category.name %>


<% if logged_in? && current_user.admin? %>
  <%= link_to "Edit", edit_category_path(@category), class: 'btn btn-warning' %>
<% end %>

<%= render 'articles/table' %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearningRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
  <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
</head>

<body style="padding: 55px 30px">
<%= render 'layouts/flash_messages' %>
<%= yield %>



<br/>
<br/>
<br/>
<hr/>
Redirect menu:
<ul>
  <li><%= link_to "Home page", root_path %></li>
  <li><%= link_to "Articles list", articles_path %></li>
  <li><%= link_to "About us", about_path %></li>
  <li><%= link_to "FAQ", faq_path %></li>
  <% if logged_in? %>
    <li><%= link_to "Logout", logout_path, method: :delete %>
      (as <strong><%= current_user.username %></strong>)
      <%= '(Is admin)' if (current_user.admin?) %>
    </li>
    <li><%= link_to "make a new article", new_article_path %></li>
  <% else %>
    <li><%= link_to "Signup", signup_path %></li>
    <li><%= link_to "Login", login_path %></li>
  <% end %>
  <li><%= link_to "Users list", users_path %></li>
  <li><%= link_to "Categories", categories_path %></li>
</ul>
</body>
</html>

app/views/pages/about.html.erb
This is the About page. you can go to the <a href="/faq">FAQ</a>

app/views/pages/faq.html.erb
This is the FAQ page. you can go to the <a href="/about">ABOUT</a>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %><br/>
  <% end %>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <p>
    <%= f.label :username %>
    <br/>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <br/>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "signup" : "Save the changes", class: 'btn btn-success') %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<p>
  You can also <%= link_to "get outta here", articles_path  %>
</p>

app/views/users/index.html.erb
<h1>Articles listing page</h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>id</th>
    <th>username</th>
    <th>email</th>
    <th>number of articles</th>
    <th>joined</th>
    <th>actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 0 %>
  <% @users.each do |user| %>
    <tr>
      <td><%= index += 1 %></td>
      <td><%= user.id %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= pluralize(user.articles.count, "article") %></td>
      <td><%= time_ago_in_words(user.created_at) + " ago" %></td>
      <td>
        <%= link_to "Visit", user_path(user), class: 'btn btn-success' %>
        <% if logged_in? %>
          <% if current_user === user || current_user.admin? %>
            <%= link_to "Edit", edit_user_path(user), class: 'btn btn-warning' %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to "Destroy this user",
                        user_path(user),
                        class: 'btn btn-danger',
                        method: :delete,
                        data: {
                          confirm: 'Are you ok with dismissing this user?'
                        }
            %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render 'form' %>

<p>
  You can also <%= link_to "get outta here", articles_path  %>
</p>

app/views/users/show.html.erb
<h1>
  <%= @user.username %>'s profile
</h1>

<%= gravatar_for @user, size: 100 %>
<% if logged_in? && current_user.id === @user.id %>
  <%= link_to "Edit your profile", edit_user_path(@user), class: 'btn btn-success' %>
  <%= link_to "Destroy your profile",
              user_path(current_user),
              method: :delete,
              class: 'btn btn-danger',
              data: {
                confirm: 'Are you fucking kidding me? you wanna destroy that ??!?'
              }
  %>
<% end %>

<table>
  <tr>
    <td width="100px">username:</td>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <td>email:</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>articles:</td>
    <td><%= pluralize(@user.articles.count, 'article') %></td>
  </tr>
</table>

<%= render 'articles/table' %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>